---
- hosts: all
  connection: local
  gather_facts: false

  pre_tasks:

  - name: "load database vars"
    include_vars: 
      file: ./clusters/localhost.yaml

  - debug: 
      msg: "template version: {{ template_version }}"

  tasks:

  - include_tasks: "./tasks/template_engine_{{ template_version }}/process_database.yaml"
    vars: 
      db: "{{ item }}"
    loop: "{{ database_list }}"
    loop_control: 
      label: "{{ item.db_name }}"


