---
- hosts: all
  connection: local
  gather_facts: false

  tasks:
    - name: Create a new database with name "acme"
      postgresql_db:
        name: acme
        #login_unix_socket: /var/run/postgresql/
  become: true
  become_user: postgres
